#!/usr/bin/env node
// Pulls every row of the Notion "Degree Audit" database and writes
// data/courses.json plus data/courses.js (the same data as a script the
// dashboard loads without a server).
//
//   NOTION_TOKEN=secret_xxx node scripts/sync-notion.mjs
//
// The token comes from a Notion internal integration that has been added to the
// Degree Audit database (••• menu → Connections). NOTION_DATA_SOURCE_ID
// overrides the default data source.
import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const DATA_SOURCE_ID = process.env.NOTION_DATA_SOURCE_ID || "8f6d8ba2-6745-48e4-8f32-0e6ea68c1244";
const NOTION_VERSION = "2025-09-03";
const root = join(dirname(fileURLToPath(import.meta.url)), "..");

function plain(richText) {
  return (richText || []).map((t) => t.plain_text).join("").trim();
}

function prop(page, name) {
  const p = page.properties[name];
  if (!p) return null;
  switch (p.type) {
    case "title": return plain(p.title) || null;
    case "rich_text": return plain(p.rich_text) || null;
    case "select": return p.select ? p.select.name : null;
    case "number": return p.number;
    case "checkbox": return p.checkbox;
    default: return null;
  }
}

export function toCourse(page) {
  return {
    id: page.id.replace(/-/g, ""),
    name: prop(page, "Course Name") || "Untitled",
    code: prop(page, "Course Code") || "",
    category: prop(page, "Category"),
    status: prop(page, "Status") || "Not Started",
    grade: prop(page, "Grade"),
    credits: prop(page, "Credits") ?? 0,
    requirement: prop(page, "Requirement"),
    term: prop(page, "Semester Taken"),
    prereqMet: Boolean(prop(page, "Prerequisite Met")),
    notes: prop(page, "Notes") || "",
    url: page.url,
  };
}

async function queryAll(token) {
  const pages = [];
  let cursor;
  do {
    const res = await fetch(`https://api.notion.com/v1/data_sources/${DATA_SOURCE_ID}/query`, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${token}`,
        "Notion-Version": NOTION_VERSION,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ page_size: 100, ...(cursor ? { start_cursor: cursor } : {}) }),
    });
    if (!res.ok) {
      throw new Error(`Notion API ${res.status}: ${await res.text()}`);
    }
    const body = await res.json();
    pages.push(...body.results);
    cursor = body.has_more ? body.next_cursor : undefined;
  } while (cursor);
  return pages;
}

async function main() {
  const token = process.env.NOTION_TOKEN;
  if (!token) {
    console.error("Set NOTION_TOKEN to a Notion integration secret that can read the Degree Audit database.");
    process.exit(1);
  }
  const pages = await queryAll(token);
  const data = {
    source: "Notion · Degree Audit",
    syncedAt: new Date().toISOString(),
    courses: pages.filter((p) => !p.in_trash && !p.archived).map(toCourse),
  };
  await writeData(data);
  console.log(`Synced ${data.courses.length} courses from Notion.`);
}

export async function writeData(data) {
  const json = JSON.stringify(data, null, 2) + "\n";
  await writeFile(join(root, "data/courses.json"), json);
  await writeFile(join(root, "data/courses.js"), `// Generated by scripts/sync-notion.mjs. Do not edit.\nwindow.DEGREE_DATA = ${json}`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main().catch((err) => {
    console.error(err.message);
    process.exit(1);
  });
}
